version: '3.7'

services:
  main-app:
    build: .  # Assuming the Dockerfile for the main application is in the current directory
    ports:
      - "8000:8000"

  tester:
    image: python:3.11-alpine
    volumes:
      - ./tests:/app/tests
    command: python -m unittest discover tests

