version: '3.7'

services:
  testing-container:
    build:
      context: .
      dockerfile: Dockerfile2
    command: python -m selenium.webdriver.chrome.service
  mainapp:
    build:
      context: .
      dockerfile: Dockerfile1
    links:
      - testing-container
    ports:
      - "8000:8000"
